django-openstack/django_openstack/dash/urls.py
# vim: tabstop=4 shiftwidth=4 softtabstop=4

# Copyright 2011 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2011 Nebula, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from django.conf.urls.defaults import *

SECURITY_GROUPS = r'^(?P<tenant_id>[^/]+)/security_groups/' \
                   '(?P<security_group_id>[^/]+)/%s$'
INSTANCES = r'^(?P<tenant_id>[^/]+)/instances/(?P<instance_id>[^/]+)/%s$'
IMAGES = r'^(?P<tenant_id>[^/]+)/images/(?P<image_id>[^/]+)/%s$'
KEYPAIRS = r'^(?P<tenant_id>[^/]+)/keypairs/%s$'
SNAPSHOTS = r'^(?P<tenant_id>[^/]+)/snapshots/(?P<instance_id>[^/]+)/%s$'
VOLUMES = r'^(?P<tenant_id>[^/]+)/volumes/(?P<volume_id>[^/]+)/%s$'
CONTAINERS = r'^(?P<tenant_id>[^/]+)/containers/%s$'
FLOATING_IPS = r'^(?P<tenant_id>[^/]+)/floating_ips/(?P<ip_id>[^/]+)/%s$'
OBJECTS = r'^(?P<tenant_id>[^/]+)/containers/(?P<container_name>[^/]+)/%s$'
NETWORKS = r'^(?P<tenant_id>[^/]+)/networks/%s$'
PORTS = r'^(?P<tenant_id>[^/]+)/networks/(?P<network_id>[^/]+)/ports/%s$'

urlpatterns = patterns('django_openstack.dash.views.instances',
    url(r'^(?P<tenant_id>[^/]+)/$', 'usage', name='dash_usage'),
    url(r'^(?P<tenant_id>[^/]+)/instances/$', 'index', name='dash_instances'),
    url(r'^(?P<tenant_id>[^/]+)/instances/refresh$', 'refresh',
        name='dash_instances_refresh'),
    url(INSTANCES % 'detail', 'detail', name='dash_instances_detail'),
    url(INSTANCES % 'console', 'console', name='dash_instances_console'),
    url(INSTANCES % 'vnc', 'vnc', name='dash_instances_vnc'),
    url(INSTANCES % 'update', 'update', name='dash_instances_update'),
)

urlpatterns += patterns('django_openstack.dash.views.security_groups',
    url(r'^(?P<tenant_id>[^/]+)/security_groups/$', 'index',
        name='dash_security_groups'),
    url(r'^(?P<tenant_id>[^/]+)/security_groups/create$', 'create',
        name='dash_security_groups_create'),
    url(SECURITY_GROUPS % 'edit_rules', 'edit_rules',
        name='dash_security_groups_edit_rules'),
)

urlpatterns += patterns('django_openstack.dash.views.images',
    url(r'^(?P<tenant_id>[^/]+)/images/$', 'index', name='dash_images'),
    url(IMAGES % 'launch', 'launch', name='dash_images_launch'),
    url(IMAGES % 'update', 'update', name='dash_images_update'),
)

urlpatterns += patterns('django_openstack.dash.views.keypairs',
    url(r'^(?P<tenant_id>[^/]+)/keypairs/$', 'index', name='dash_keypairs'),
    url(KEYPAIRS % 'create', 'create', name='dash_keypairs_create'),
    url(KEYPAIRS % 'import', 'import_keypair', name='dash_keypairs_import'),
)

urlpatterns += patterns('django_openstack.dash.views.floating_ips',
    url(r'^(?P<tenant_id>[^/]+)/floating_ips/$', 'index',
        name='dash_floating_ips'),
    url(FLOATING_IPS % 'associate', 'associate',
        name='dash_floating_ips_associate'),
    url(FLOATING_IPS % 'disassociate', 'disassociate',
        name='dash_floating_ips_disassociate'),
)

urlpatterns += patterns('django_openstack.dash.views.snapshots',
    url(r'^(?P<tenant_id>[^/]+)/snapshots/$', 'index', name='dash_snapshots'),
    url(SNAPSHOTS % 'create', 'create', name='dash_snapshots_create'),
)

urlpatterns += patterns('django_openstack.dash.views.volumes',
    url(r'^(?P<tenant_id>[^/]+)/volumes/$', 'index', name='dash_volumes'),
    url(r'^(?P<tenant_id>[^/]+)/volumes/create', 'create',
            name='dash_volumes_create'),
    url(VOLUMES % 'attach', 'attach', name='dash_volumes_attach'),
    url(VOLUMES % 'detail', 'detail', name='dash_volumes_detail'),
)

# Swift containers and objects.
urlpatterns += patterns('django_openstack.dash.views.containers',
    url(CONTAINERS % '', 'index', name='dash_containers'),
    url(CONTAINERS % 'create', 'create', name='dash_containers_create'),
)

urlpatterns += patterns('django_openstack.dash.views.objects',
    url(OBJECTS % '', 'index', name='dash_objects'),
    url(OBJECTS % 'upload', 'upload', name='dash_objects_upload'),
    url(OBJECTS % '(?P<object_name>[^/]+)/copy',
        'copy', name='dash_object_copy'),
    url(OBJECTS % '(?P<object_name>[^/]+)/download',
        'download', name='dash_objects_download'),
)

urlpatterns += patterns('django_openstack.dash.views.networks',
    url(r'^(?P<tenant_id>[^/]+)/networks/$', 'index', name='dash_networks'),
    url(NETWORKS % 'create', 'create', name='dash_network_create'),
    url(NETWORKS % '(?P<network_id>[^/]+)/detail', 'detail',
        name='dash_networks_detail'),
    url(NETWORKS % '(?P<network_id>[^/]+)/rename', 'rename',
        name='dash_network_rename'),
)

urlpatterns += patterns('django_openstack.dash.views.ports',
    url(PORTS % 'create', 'create', name='dash_ports_create'),
    url(PORTS % '(?P<port_id>[^/]+)/attach', 'attach',
        name='dash_ports_attach'),
)

django-openstack/django_openstack/urls.py
# vim: tabstop=4 shiftwidth=4 softtabstop=4

# Copyright 2011 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2011 Nebula, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from django.conf.urls.defaults import patterns, url, include
from django.conf import settings
from django_openstack.signals import *
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^auth/', include('django_openstack.auth.urls')),
    url(r'^dash/', include('django_openstack.dash.urls')),
    url(r'^syspanel/', include('django_openstack.syspanel.urls')),
    url(r'^settings/$', TemplateView.as_view(
                template_name='django_openstack/dash/settings.html'),
                name='dashboard_settings')

)

# import urls from modules
for module_urls in dash_modules_urls.send(sender=dash_modules_urls):
    urlpatterns += module_urls[1].urlpatterns

django-openstack/django_openstack/dash/views/networks.py
# vim: tabstop=4 shiftwidth=4 softtabstop=4

# Copyright 2011 United States Government as represented by the
# Administrator of the National Aeronautics and Space Administration.
# All Rights Reserved.
#
# Copyright 2011 Nebula, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

"""
Views for managing api.quantum_api(request) networks.
"""
import logging

from django import http
from django import shortcuts
from django import template
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from django.utils.translation import ugettext as _

from django_openstack import forms
from django_openstack import api

from django_openstack.dash.views.ports import DeletePort
from django_openstack.dash.views.ports import DetachPort
from django_openstack.dash.views.ports import TogglePort

import warnings


LOG = logging.getLogger('django_openstack.dash.views.networks')


class CreateNetwork(forms.SelfHandlingForm):
    name = forms.CharField(required=True, label=_("Network Name"))

    def handle(self, request, data):
        network_name = data['name']

        try:
            LOG.info('Creating network %s ' % network_name)
            send_data = {'network': {'name': '%s' % network_name}}
            api.quantum_create_network(request, send_data)
        except Exception, e:
            messages.error(request,
                           _('Unable to create network %(network)s: %(msg)s') %
                           {"network": network_name, "msg": e.message})
            return shortcuts.redirect(request.build_absolute_uri())
        else:
            msg = _('Network %s has been created.') % network_name
            LOG.info(msg)
            messages.success(request, msg)
            return shortcuts.redirect('dash_networks',
                                      tenant_id=request.user.tenant_id)


class DeleteNetwork(forms.SelfHandlingForm):
    network = forms.CharField(widget=forms.HiddenInput())

    def handle(self, request, data):
        try:
            LOG.info('Deleting network %s ' % data['network'])
            api.quantum_delete_network(request, data['network'])
        except Exception, e:
            messages.error(request,
                    _('Unable to delete network %(network)s: %(msg)s') %
                    {"network": data['network'], "msg": e.message})
        else:
            msg = _('Network %s has been deleted.') % data['network']
            LOG.info(msg)
            messages.success(request, msg)

        return shortcuts.redirect(request.build_absolute_uri())


class RenameNetwork(forms.SelfHandlingForm):
    network = forms.CharField(widget=forms.HiddenInput())
    new_name = forms.CharField(required=True)

    def handle(self, request, data):
        try:
            LOG.info('Renaming network %s to %s' %
                     (data['network'], data['new_name']))
            send_data = {'network': {'name': '%s' % data['new_name']}}
            api.quantum_update_network(request, data['network'], send_data)
        except Exception, e:
            messages.error(request,
                    _('Unable to rename network %(network)s: %(msg)s') %
                    {"network": data['network'], "msg": e.message})
        else:
            msg = _('Network %(net)s has been renamed to %(new_name)s.') % {
                  "net": data['network'], "new_name": data['new_name']}
            LOG.info(msg)
            messages.success(request, msg)

        return shortcuts.redirect(request.build_absolute_uri())


@login_required
def index(request, tenant_id):
    delete_form, delete_handled = DeleteNetwork.maybe_handle(request)

    networks = []
    instances = []

    try:
        networks_list = api.quantum_list_networks(request)
        details = []
        for network in networks_list['networks']:
            net_stats = _calc_network_stats(request, tenant_id, network['id'])
            # Get network details like name and id
            details = api.quantum_network_details(request, network['id'])
            networks.append({
                'name': details['network']['name'],
                'id': network['id'],
                'total': net_stats['total'],
                'available': net_stats['available'],
                'used': net_stats['used'],
                'tenant': tenant_id
            })

    except Exception, e:
        messages.error(request,
                       _('Unable to get network list: %s') % e.message)

    return shortcuts.render_to_response(
    'django_openstack/dash/networks/index.html', {
        'networks': networks,
        'delete_form': delete_form,
    }, context_instance=template.RequestContext(request))


@login_required
def create(request, tenant_id):
    network_form, handled = CreateNetwork.maybe_handle(request)
    if handled:
        return shortcuts.redirect('dash_networks', request.user.tenant_id)

    return shortcuts.render_to_response(
    'django_openstack/dash/networks/create.html', {
        'network_form': network_form
    }, context_instance=template.RequestContext(request))


@login_required
def detail(request, tenant_id, network_id):
    delete_port_form, delete_handled = DeletePort.maybe_handle(request)
    detach_port_form, detach_handled = DetachPort.maybe_handle(request)
    toggle_port_form, port_toggle_handled = TogglePort.maybe_handle(request)

    network = {}

    try:
        network_details = api.quantum_network_details(request, network_id)
        network['name'] = network_details['network']['name']
        network['id'] = network_id
        network['ports'] = _get_port_states(request, tenant_id, network_id)
    except Exception, e:
        messages.error(request,
                       _('Unable to get network details: %s') % e.message)

    return shortcuts.render_to_response(
    'django_openstack/dash/networks/detail.html', {
        'network': network,
        'tenant': tenant_id,
        'delete_port_form': delete_port_form,
        'detach_port_form': detach_port_form,
        'toggle_port_form': toggle_port_form
    }, context_instance=template.RequestContext(request))


@login_required
def rename(request, tenant_id, network_id):
    rename_form, handled = RenameNetwork.maybe_handle(request)
    network_details = api.quantum_network_details(request, network_id)

    if handled:
        return shortcuts.redirect('dash_networks', request.user.tenant_id)

    return shortcuts.render_to_response(
    'django_openstack/dash/networks/rename.html', {
        'network': network_details,
        'rename_form': rename_form
    }, context_instance=template.RequestContext(request))


def _get_port_states(request, tenant_id, network_id):
    """
    Helper method to find port states for a network
    """
    network_ports = []
    # Get all vifs for comparison with port attachments
    vifs = api.get_vif_ids(request)

    # Get all ports on this network
    ports = api.quantum_list_ports(request, network_id)
    for port in ports['ports']:
        port_details = api.quantum_port_details(request,
                                                network_id, port['id'])
        # Get port attachments
        port_attachment = api.quantum_port_attachment(request,
                                                      network_id, port['id'])
        # Find instance the attachment belongs to
        connected_instance = None
        if port_attachment['attachment']:
            for vif in vifs:
                if str(vif['id']) == str(port_attachment['attachment']['id']):
                    connected_instance = vif['instance_name']
                    break
        network_ports.append({
            'id': port_details['port']['id'],
            'state': port_details['port']['state'],
            'attachment': port_attachment['attachment'],
            'instance': connected_instance
        })
    return network_ports


def _calc_network_stats(request, tenant_id, network_id):
    """
    Helper method to calculate statistics for a network
    """
    # Get all ports statistics for the network
    total = 0
    available = 0
    used = 0
    ports = api.quantum_list_ports(request, network_id)
    for port in ports['ports']:
        total += 1
        # Get port attachment
        port_attachment = api.quantum_port_attachment(request,
                                                      network_id, port['id'])
        if port_attachment['attachment']:
            used += 1
        else:
            available += 1

    return {'total': total, 'used': used, 'available': available}

django-openstack/django_openstack/templates/django_openstack/dash/networks/_delete.html
{%load i18n%}
<form id="delete_form" class="form-delete" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{hidden}}
  {% endfor %}
  <input name="network" type="hidden" value="{{network.id}}" />
  <input title="Network" id="delete_{{network.id}}" class="delete" type="submit" value="{% trans "Delete"%}" />
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_delete_port.html
{%load i18n%}
<form id="delete_port_form" class="form-delete" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{hidden}}
  {% endfor %}
  <input name="network" type="hidden" value="{{network.id}}" />
  <input name="port" type="hidden" value="{{port.id}}" />
  <input title="Delete this port" id="delete_{{port.id}}" class="delete" type="submit" value="{% trans "Delete"%}" />
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_detach_port.html
{%load i18n%}
<form id="detach_port_form" class="form-detach" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{hidden}}
  {% endfor %}
  <input name="network" type="hidden" value="{{network.id}}" />
  <input name="port" type="hidden" value="{{port.id}}" />
  <input title="Detach port from instance" id="detach_{{port.id}}" class="detach" type="submit" value="{% trans "Detach"%}" />
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_detail.html
{%load i18n%}
<table id='Ports' class="wide">
  <tr id='headings'>
    <th>{% trans "ID"%}</th>
    <th>{% trans "State"%}</th>
    <th>{% trans "Attachment"%}</th>
    <th>{% trans "Actions"%}</th>
    <th>{% trans "Extensions"%}</th>
  </tr>
  <tbody class='main'>
    {% for port in network.ports %}
      <tr class="{% cycle 'odd' 'even' %}">
          <td>{{port.id}}</td>
          <td class="{{port.state}}">{{port.state}}</td>
          <td>
            {% if port.attachment %}
            <table class="attachmend_details">
                <tr>
                    <td>{% trans "Instance"%}</td>
                    <td>{% trans "VIF Id"%}</td>
                </tr>
                <tr>
                    <td> {{port.instance}} </td>
                    <td> {{port.attachment.id}} </td>
                </tr>
            </table>
            {% else %}
            --
            {% endif %}
          </td>
          <td id="actions">
            <ul>
              {% if port.attachment %}
              <li class="form">{% include "django_openstack/dash/networks/_detach_port.html" with form=detach_port_form %}</li>
              {% else %}
              <li><a href='{% url dash_ports_attach request.user.tenant_id network.id port.id %}'>{% trans "Attach"%}</a></li>
              {% endif %}
              <li class="form">{% include "django_openstack/dash/networks/_delete_port.html" with form=delete_port_form %}</li>
              <li class="form">{% include "django_openstack/dash/networks/_toggle_port.html" with form=toggle_port_form %}</li>
            </ul>
          </td>
          <td id="extensions">
            <ul>
            </ul>
          </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_form.html
{%load i18n%}
<form id="network_form" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    {% for field in form.visible_fields %}
    {{ field.label_tag }}
    {{ field.errors }}
    {{ field }}
  {% endfor %}
  <input type="submit" value="{% trans "Create Network" %}" class="large-rounded" />
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_list.html
{%load i18n%}
<table id='networks' class="wide">
  <tr id='headings'>
    <th>{% trans "ID"%}</th>
    <th>{% trans "Name"%}</th>
    <th>{% trans "Ports"%}</th>
    <th>{% trans "Available"%}</th>
    <th>{% trans "Used"%}</th>
    <th>{% trans "Action"%}</th>
  </tr>
  <tbody class='main'>
    {% for network in networks %}
      <tr class="{% cycle 'odd' 'even' %}" id="{{network.id}}">
          <td><a href='{% url dash_networks_detail request.user.tenant_id network.id %}'>{{network.id}}</a></td>
          <td class="name">{{network.name}}</td>
          <td>{{network.total}}</td>
          <td>{{network.available}}</td>
          <td>{{network.used}}</td>
          <td id="actions">
            <ul>
              <li class="form">{% include "django_openstack/dash/networks/_delete.html" with form=delete_form %}</li>
              <li><a href='{% url dash_network_rename request.user.tenant_id network.id %}'>{% trans "Rename"%}</a></li>
            </ul>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_rename.html
{%load i18n%}
<form id="form_rename_{{network.id}}" class="form-rename" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{hidden}}
  {% endfor %}

  <input name="network" type="hidden" value="{{network.id}}" />
  <input id="new_name_{{network.id}}" name="new_name" type="hidden" value="{{network.name}}" />

  <input id="rename_{{network.id}}" class="rename" type="submit" value="{% trans "Rename"%}" />

  <div class="network_rename_div" id="rename_div_{{network.id}}">
      <input id="change_to_{{network.id}}" name="change_to" class="change_to ui-corner-all ui-state-highlight" size="20" value="{{network.name}}"/><br/><br/>
      <button id="{{network.id}}" class="dialog_rename">{% trans "Rename"%}</button>
  </div>

</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_rename_form.html
{%load i18n%}
<form id="rename_form" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    {% for field in form.visible_fields %}
    {{ field.label_tag }}
    {{ field.errors }}
    {{ field }}
  {% endfor %}
  <input type="hidden" name="network" value="{{network.network.id}}"/>
  <input type="submit" value="{% trans "Rename Network"%}" class="large-rounded" />
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/_toggle_port.html
{%load i18n%}
<form id="port_toggle_form" class="form-toggle" method="post">
  {% csrf_token %}
  {% for hidden in form.hidden_fields %}
    {{hidden}}
  {% endfor %}
  <input name="network" type="hidden" value="{{network.id}}" />
  <input name="port" type="hidden" value="{{port.id}}" />
  {% if port.state == 'DOWN' %}
    <input name="state" type="hidden" value="ACTIVE" />
    <input title="Turn port UP" id="port_up_{{port.id}}" class="port_up" type="submit" value="{% trans "Port UP"%}" />
  {% else %}
    <input name="state" type="hidden" value="DOWN" />
    <input title="Turn port DOWN" id="port_up_{{port.id}}" class="port_down" type="submit" value="{% trans "Port DOWN"%}" />
  {% endif %}
</form>

django-openstack/django_openstack/templates/django_openstack/dash/networks/create.html
{% extends 'django_openstack/dash/base.html' %}
{%load i18n%}

{% block sidebar %}
  {% with current_sidebar="networks" %}
    {{block.super}}
  {% endwith %}
{% endblock %}

{% block page_header %}
  {# to make searchable false, just remove it from the include statement #}
  {% include "django_openstack/common/_page_header.html" with title=_("Create Network") %}
{% endblock page_header %}

{% block dash_main %}
  <div class="dash_block">
    <div class="left">
      {% include 'django_openstack/dash/networks/_form.html' with form=network_form %}
      <h3><a href="{% url dash_networks request.user.tenant_id %}"><< {% trans "Return to networks list"%}</a></h3>
    </div>

    <div class="right">
      <h3>{% trans "Description"%}:</h3>
      <p>{% trans "Networks provide layer 2 connectivity to your instances."%}</p>
    </div>
    <div class="clear">&nbsp;</div>
  </div>
{% endblock %}

django-openstack/django_openstack/templates/django_openstack/dash/networks/detail.html
{% extends 'django_openstack/dash/base.html' %}
{%load i18n%}

{% block sidebar %}
  {% with current_sidebar="networks" %}
    {{block.super}}
  {% endwith %}
{% endblock %}

{% block page_header %}
  {% url dash_networks_detail request.user.tenant_id network.id as refresh_link %}
  {# to make searchable false, just remove it from the include statement #}
  {% include "django_openstack/common/_page_header.html" with title=network.name refresh_link=refresh_link searchable="true" %}
{% endblock page_header %}

{% block breadcrumbs %}
    <a href="{% url dash_networks tenant %}">Networks</a>&nbsp;&raquo;&nbsp;
    <a href="{% url dash_networks_detail tenant network.id %}">{{network.name}}</a>
{% endblock %}

{% block dash_main %}
  {% if network.ports %}
    {% include 'django_openstack/dash/networks/_detail.html' %}
    <a id="network_create_link" class="action_link large-rounded" href="{% url dash_ports_create request.user.tenant_id network.id %}">{% trans "Create Ports"%}</a>
  {% else %}
    <div class="message_box info">
     <h2>{% trans "Info"%}</h2>
     <p>{% trans "There are currently no ports in this network."%} <a href="{% url dash_ports_create request.user.tenant_id network.id %}">{% trans "Create Ports"%} &gt;&gt;</a></p>
    </div>
  {% endif %}
{% endblock %}

django-openstack/django_openstack/templates/django_openstack/dash/networks/index.html
{% extends 'django_openstack/dash/base.html' %}
{%load i18n%}

{% block sidebar %}
  {% with current_sidebar="networks" %}
    {{block.super}}
  {% endwith %}
{% endblock %}

{% block page_header %}
  {% url dash_networks request.user.tenant_id as refresh_link %}
  {# to make searchable false, just remove it from the include statement #}
  {% include "django_openstack/common/_page_header.html" with title=_("Networks") refresh_link=refresh_link searchable="true" %}
{% endblock page_header %}

{% block dash_main %}
  {% if networks %}
    {% include 'django_openstack/dash/networks/_list.html' %}
    {% url dash_network_create request.user.tenant_id as dash_net_url %}
    <a id="network_create_link" class="action_link large-rounded" href="{{dash_net_url}}">{% trans "Create New Network"%}</a>
  {% else %}
    <div class="message_box info">
      <h2>{% trans "Info"%}</h2>
      <p>{% trans "There are currently no networks."%} <a href='{% url dash_network_create request.user.tenant_id %}'>{% trans "Create A Network"%} &gt;&gt;</a></p>
    </div>
  {% endif %}
  </div>
{% endblock %}

django-openstack/django_openstack/templates/django_openstack/dash/networks/rename.html
{% extends 'django_openstack/dash/base.html' %}
{%load i18n%}

{% block sidebar %}
  {% with current_sidebar="networks" %}
    {{block.super}}
  {% endwith %}
{% endblock %}

{% block page_header %}
  {# to make searchable false, just remove it from the include statement #}
  {% include "django_openstack/common/_page_header.html" with title=_("Rename Network") %}
{% endblock page_header %}

{% block headerjs %}
<script type="text/javascript">
    $(document).ready(function() {
        $('input#id_new_name').val('{{network.network.name}}');
    });
</script>
{% endblock headerjs %}

{% block dash_main %}
  <div class="dash_block">
    <div class="left">
      {% include 'django_openstack/dash/networks/_rename_form.html' with form=rename_form %}
      <h3><a href="{% url dash_networks request.user.tenant_id %}"><< {% trans "Return to networks list"%}</a></h3>
    </div>

    <div class="right">
      <h3>{% trans "Rename"%}:</h3>
      <p>{% trans "Enter a new name for your network."%}</p>
    </div>
    <div class="clear">&nbsp;</div>
  </div>
{% endblock %}